### ISSUE TITLE
problem in config.yml

### ISSUE THREAD

**Issue by BenArfanour** [ahmetakbn/PianoSoloWeatherBundle#4]
unrecognized options "download_csv, cache" under "pianosolo_weather" ???

**Comment by codebach** [comment]
these options `(download_csv, cache)` are not under `pianosolo_weather`. They must be under `options`
Please make sure your configurations are like this:
```yaml
piano_solo_weather:
    api_key: "YourApiKey" # Required (OpenWeatherMap Api Key)
    options:
        download_csv: false # Default True
        cache: true # Default False (To use cache the system needs Php-Apc cache)
```
