### ISSUE TITLE
Deprecation in Symfony 3.2+

### ISSUE THREAD

**Issue by tetele** [ahmetakbn/PianoSoloWeatherBundle#5]
I get a deprecation error in Symfony 3.4:
```
Using a colon after an unquoted mapping key that is not followed by an indication character (i.e. " ", ",", "[", "]", "{", "}") is deprecated since Symfony 3.2 and will throw a ParseException in 4.0 in "/path/to/app/vendor/pianosolo/weather-bundle/PianoSolo/WeatherBundle/DependencyInjection/../Resources/config/services.yml" on line 26.
```

This is due to the fact that in `PianoSolo/WeatherBundle/Resources/config/services.yml` on lines 21-26 we have

```
    # PianoSolo Weather Twig Extension Service
     pianosolo.weather.twig.weather:
         class: PianoSolo\WeatherBundle\Twig\WeatherExtension
         arguments: ["@pianosolo.weather","%pianosolo.weather.options.download_csv%"]
         tags:
             - { name:twig.extension }
```

notice the `name:twig.extension` part, without a blank between `name:` and `twig extension`. A space there would probably fix the issue.
